<a href="https://colab.research.google.com/github/DeepakMalapaka/ML/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1

In [1]:
import numpy as np

1.	Perform arithmetic operations on NumPy arrays.

In [2]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addtion:",np.add(a,b))
print("Subtraction:",np.subtract(a,b))
print("Multiplication:",np.multiply(a,b))
print("Division:",np.divide(a,b))

Addtion: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


2.	Write a script to compute the mean and standard deviation of a NumPy array.

In [6]:
a1=np.array([1,2,3,4,5])
print("Mean:",np.mean(a1))
print("Standard Deviation:",np.std(a1))

Mean: 3.0
Standard Deviation: 1.4142135623730951


3.	Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [5]:
a2=np.arange(10,51,5)
print(a2)

[10 15 20 25 30 35 40 45 50]


4.	Reshape the array into a 2x4 matrix

In [4]:
a3=np.array([1,2,3,4,5,6,7,8])
a3=a3.reshape(2,4)
print(a3)

[[1 2 3 4]
 [5 6 7 8]]


5.	Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

•	Extract the sub-matrix containing the last two rows and first two columns.

•	Replace all elements greater than 4 with 0.


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1:,:2])
arr[arr>4]=0
print(arr)


[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


6.	Create two 1D arrays:

•	a = np.array([1, 2, 3])

•	b = np.array([4, 5, 6])

•	Perform element-wise addition, multiplication, and division.


In [8]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",np.add(a,b))
print("Multiplication:",np.multiply(a,b))
print("Division:",np.divide(a,b))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


7.	Create a random NumPy array of size (4, 4). Compute:

•	Mean of each column.

•	Maximum value of the entire array.

•	Sum of all elements.


In [9]:
a=np.random.randint(10,size=(4,4))
print(a)
print("Mean of each column:",np.mean(a,axis=0))
print("Maximum value of the entire array:",np.max(a))

[[5 4 2 7]
 [6 3 8 7]
 [3 9 4 2]
 [3 3 4 3]]
Mean of each column: [4.25 4.75 4.5  4.75]
Maximum value of the entire array: 9


8.	Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.

In [10]:
arr = np.array([1, 2, 3, 4])
arr=arr+10
arr=arr*2
print(arr)

[22 24 26 28]


9.	Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100. Perform the following:

•	Extract the second "layer" (i.e., the second 2D array) in the first dimension.

• Extract the first two rows and the last three columns from each "layer."

•	Replace all elements divisible by 3 with -1.


In [ ]:
arr=np.random.randint(1,101,size=(3,4,5))
print(arr)
print(arr[1])
print(arr[0][0:2,-3:])
arr[arr%3==0]=-1
print(arr)

10.	Work with broadcasting and advanced operations in NumPy.
      Create a NumPy array arr of shape (3, 3) with random integers between        1 and 20. Perform the following:

•	Subtract the mean of each row from its respective elements (row-wise normalization).

•	Create a new array by squaring all the elements in arr.

•	Find the indices of the top 3 maximum values in the entire array.
